name: Push tag version
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@master
      - name: Publish tag to registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker version
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
          docker build -t identw/hetzner-cloud-controller-manager:$RELEASE_VERSION .
          docker push identw/hetzner-cloud-controller-manager:$RELEASE_VERSION
